dist: trusty
languaje: java
jdk:
- oraclejdk8
before install:
- mvn install -DskipTests=true Dmaven.javadoc.skip=true -B -V
- pip install --user codecov
script:
- mvn deploy --settings settings.xml
after success:
- codecov
cache:
    directories:
    - ".autoconf"
    - "$HOME/.m2"

